Organizations:  
  - &Org4
    Name: Org4
    ID: Org4MSP
    MSPDir: ../../identities/peerOrganizations/org4.testbed.local/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('Org4MSP.admin', 'Org4MSP.peer', 'Org4MSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('Org4MSP.admin', 'Org4MSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('Org4MSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('Org4MSP.peer')"
