volumes:
  orderer_ord3_data:

networks:
  fabric_net:
    name: fabric_net

services:
  orderer.ord3.testbed.local:
    container_name: orderer.ord3.testbed.local
    image: hyperledger/fabric-orderer:${FABRIC_VERSION}
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LOCALMSPID=Ord3MSP
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=9050
      - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:9053
      - ORDERER_OPERATIONS_LISTENADDRESS=0.0.0.0:9442
    working_dir: /root
    command: orderer
    volumes:
      - ../config/orderer.yaml:/etc/hyperledger/fabric/orderer.yaml
      - ../organizations/ordererOrganizations/ord3.testbed.local/orderers/orderer.ord3.testbed.local/:/etc/hyperledger/fabric
      - orderer_ord3_data:/var/hyperledger
    ports:
      - 9050:9050
      - 9053:9053
      - 9442:9442
    networks:
      - fabric_net