volumes:
  peer0_org2_data:

networks:
  fabric_net:
    name: fabric_net

services:
  peer0.org2.testbed.local:
    container_name: peer0.org2.testbed.local
    image: hyperledger/fabric-peer:${FABRIC_VERSION}
    labels:
      service: hyperledger-fabric
    environment:
      # General variables
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_net
      # Peer specific variables
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_PEER_ID=peer0.org2.testbed.local
      - CORE_PEER_ADDRESS=peer0.org2.testbed.local:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org2.testbed.local:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.testbed.local:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.testbed.local:8051
      - CORE_OPERATIONS_LISTENADDRESS=peer0.org2.testbed.local:9446
    working_dir: /root
    command: peer node start
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../config/core.yaml:/etc/hyperledger/fabric/core.yaml
      - ../organizations/peerOrganizations/org2.testbed.local/peers/peer0.org2.testbed.local/msp:/etc/hyperledger/fabric/msp
      - ../organizations/peerOrganizations/org2.testbed.local/peers/peer0.org2.testbed.local/tls:/etc/hyperledger/fabric/tls
      - peer0_org2_data:/var/hyperledger/production
    ports:
      - 8051:8051
      - 9446:9446
    networks:
      - fabric_net