volumes:
  peer0_org3_data:

networks:
  fabric_net:
    name: fabric_net

services:
  peer0.org3.testbed.local:
    container_name: peer0.org3.testbed.local
    image: hyperledger/fabric-peer:${FABRIC_VERSION}
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_net
      # enabled TLS
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer0.org3.testbed.local
      - CORE_PEER_ADDRESS=peer0.org3.testbed.local:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org3.testbed.local:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org3.testbed.local:9051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org3.testbed.local:9051
      - CORE_PEER_LOCALMSPID=Org3MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_OPERATIONS_LISTENADDRESS=peer0.org3.testbed.local:9447
      - CORE_METRICS_PROVIDER=prometheus
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer0org3"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
    working_dir: /root
    command: peer node start
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ../config/core.yaml:/etc/hyperledger/fabric/core.yaml
      - ../organizations/peerOrganizations/org3.testbed.local/peers/peer0.org3.testbed.local/msp:/etc/hyperledger/fabric/msp
      - ../organizations/peerOrganizations/org3.testbed.local/peers/peer0.org3.testbed.local/tls:/etc/hyperledger/fabric/tls
      - peer0_org3_data:/var/hyperledger/production
    ports:
      - 9051:9051
      - 9447:9447
    networks:
      - fabric_net
