volumes:
  orderer_ord2_data:

networks:
  fabric_net:
    name: fabric_net

services:
  orderer.ord2.testbed.local:
    container_name: orderer.ord2.testbed.local
    image: hyperledger/fabric-orderer:${FABRIC_VERSION}
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LOCALMSPID=Ord2MSP
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=8050
      - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:8053
      - ORDERER_OPERATIONS_LISTENADDRESS=0.0.0.0:9444
    working_dir: /root
    command: orderer
    volumes:
      - ../config/orderer.yaml:/etc/hyperledger/fabric/orderer.yaml
      - ../organizations/ordererOrganizations/ord2.testbed.local/orderers/orderer.ord2.testbed.local/msp/:/etc/hyperledger/fabric/msp
      - ../organizations/ordererOrganizations/ord2.testbed.local/orderers/orderer.ord2.testbed.local/tls/:/etc/hyperledger/fabric/tls
      - orderer_ord2_data:/var/hyperledger/production/orderer
    ports:
      - 8050:8050
      - 8053:8053
      - 9444:9444
    networks:
      - fabric_net