# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

PeerOrgs:
  # ---------------------------------------------------------------------------
  # Organization template
  # ---------------------------------------------------------------------------
  - Name: ${ORG_NAME}
    Domain: ${ORG_DOMAIN}
    EnableNodeOUs: true
    Template:
      Count: ${PEER_COUNT}
      SANS:
        - localhost
    Users:
      Count: ${USER_COUNT}