# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:
  - &${ORG_NAME}
    Name: ${ORG_NAME}MSP
    ID: ${ORG_NAME}MSP
    MSPDir: ../organizations/peerOrganizations/${ORG_DOMAIN}/msp
    Policies:
      Readers:
          Type: Signature
          Rule: "OR('${ORG_NAME}MSP.admin', '${ORG_NAME}MSP.peer', '${ORG_NAME}MSP.client')"
      Writers:
          Type: Signature
          Rule: "OR('${ORG_NAME}MSP.admin', '${ORG_NAME}MSP.client')"
      Admins:
          Type: Signature
          Rule: "OR('${ORG_NAME}MSP.admin')"
      Endorsement:
          Type: Signature
          Rule: "OR('${ORG_NAME}MSP.peer')"
