# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

PeerOrgs:
  # ---------------------------------------------------------------------------
  # Organization template
  # ---------------------------------------------------------------------------
  - Name: Org4
    Domain: org4.testbed.local
    EnableNodeOUs: true
    Template:
      Count: 1
      SANS:
        - localhost
    Users:
      Count: 1