OrdererOrgs:
# Mock up organization that will have control over orderers
- Name: OrdererOrgName
  Domain: ord.testbed.local
  EnableNodeOUs: true #adds OU=admin|client to certificate (used for POLICIES)
  Specs:
  - Hostname: orderer2
    SANS:
      - localhost
  - Hostname: orderer1
    SANS:
      - localhost
PeerOrgs:
- Name: Org1Name
  Domain: org1.testbed.local
  EnableNodeOUs: true
  Template:
    Count: 1
    SANS:
      - localhost
  Users:
    Count: 3
- Name: Org2Name
  Domain: org2.testbed.local
  EnableNodeOUs: true
  Template:
    Count: 1
    SANS:
      - localhost
  Users:
    Count: 1
- Name: Org3Name
  Domain: org3.testbed.local
  EnableNodeOUs: true
  Template:
    Count: 1
    SANS:
      - localhost
  Users:
    Count: 1
