OrdererOrgs:
  - Name: Ord1
    Domain: ord1.testbed.local
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer
        SANS:
          - localhost # Alternative name for the orderer
          - hlf1.disi.unitn.it