PeerOrgs:
  - Name: Org1
    Domain: org1.testbed.local
    EnableNodeOUs: true
    Template: 
      Count: 1 # Number of peers per organization
      SANS:
        - localhost
    Users:
      Count: 3 # Number of users (excluding admin) per organization