PeerOrgs:
  - Name: Org2
    Domain: org2.testbed.local
    EnableNodeOUs: true
    Template: 
      Count: 1 # Number of peers per organization
      SANS:
        - localhost
    Users:
      Count: 2 # Number of users (excluding admin) per organization