PeerOrgs:
  - Name: Org3
    Domain: org3.testbed.local
    EnableNodeOUs: true
    Template: 
      Count: 1 # Number of peers per organization
      SANS:
        - localhost
    Users:
      Count: 4 # Number of users (excluding admin) per organization