name: "Minimal Fabric Benchmark Network"
version: "2.0.0"

caliper:
  blockchain: fabric

channels:
  - channelName: mychannel
    contracts:
      - id: cc-test

organizations:
  - mspid: Org1MSP
    identities:
      certificates:
        - name: Admin
          admin: true
          clientPrivateKey:
            path: ../organizations/peerOrganizations/org1.testbed.local/users/Admin@org1.testbed.local/msp/keystore/priv_sk
          clientSignedCert:
            path: ../organizations/peerOrganizations/org1.testbed.local/users/Admin@org1.testbed.local/msp/signcerts/Admin@org1.testbed.local-cert.pem
    connectionProfile:
      path: ../organizations/peerOrganizations/org1.testbed.local/connection-org1.json
      discover: true
  - mspid: Org2MSP
    identities:
      certificates:
        - name: User1
          admin: false
          clientPrivateKey:
            path: ../organizations/peerOrganizations/org2.testbed.local/users/User1@org2.testbed.local/msp/keystore/priv_sk
          clientSignedCert:
            path: ../organizations/peerOrganizations/org2.testbed.local/users/User1@org2.testbed.local/msp/signcerts/User1@org2.testbed.local-cert.pem
    connectionProfile:
      path: ../organizations/peerOrganizations/org2.testbed.local/connection-org2.json
      discover: true
  - mspid: Org3MSP
    identities:
      certificates:
        - name: User1
          admin: false
          clientPrivateKey:
            path: ../organizations/peerOrganizations/org3.testbed.local/users/User1@org3.testbed.local/msp/keystore/priv_sk
          clientSignedCert:
            path: ../organizations/peerOrganizations/org3.testbed.local/users/User1@org3.testbed.local/msp/signcerts/User1@org3.testbed.local-cert.pem
    connectionProfile:
      path: ../organizations/peerOrganizations/org3.testbed.local/connection-org3.json
      discover: true